### PR TITLE
Fix psuedo-bridge recipe

### PR DESCRIPTION
**Pull request by patricktokeeffe**
Use correct file format, not directory path.

### CODE REVIEW

**Comment by patricktokeeffe** [comment]
These recipes were rather difficult to locate, btw, fwiw.

**Comment by nmav** [comment]
There is a typo on the commit message: psuedo -> pseudo

**Comment by nmav** [comment]
How did you find them? They are linked from https://ocserv.gitlab.io/www/recipes.html

**Comment by nmav** [comment]
Other than the typo in the commit message the change looks good to me

**Comment by patricktokeeffe** [comment]
Better in the message than source 😁 I kid. 

The recipe page that comes up via search engine is apparently stale? http://www.infradead.org/ocserv/recipes-ocserv-pseudo-bridge.html

**Comment by nmav** [comment]
http://www.infradead.org/ocserv/ should redirect to https://ocserv.gitlab.io/www/
(it seems it does for every page except this one)

**Comment by nmav** [comment]
Would you amend the commit message?

**Pull request merged**
